config/routes.rb
RailsTest::Application.routes.draw do
  get "oauths/oauth"
  get "oauths/callback"
  resources :answers

  resources :questions do
    resources :answers, :shallow => true
  end

  resources :tests do
    resources :questions, :shallow => true
  end

  resources :articles

  resources :posts

  resources :courses do 
    resources :tests, :shallow => true
    resources :articles, :shallow => true
  end


  root to: 'welcome#index'

  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  #resources :users
  post 'users' => "users#create"
  resources :sessions
  resources :password_resets

  scope "/admin" do
    resources :users
    get '/categories' => 'categories#admin_index'
    get '/courses' => 'courses#admin_index'
    get '/tests' => 'tests#admin_index'
  end

  resources :categories, :except => [:admin_index] do
    collection do
      get :manage

      # required for Sortable GUI server side actions
      post :rebuild
    end
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base

  belongs_to :question

end

app/models/article.rb
class Article < ActiveRecord::Base

  attr_accessible :title, :short, :full, :picture, :state, :created_at, :updated_at, :course_id

  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  #validates_attachment_presence :picture

  validates_presence_of :title, :state, :course

  belongs_to :course

  include TesterModels::StateMachine

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  attr_accessible :user_id, :provider, :uid
  belongs_to :user
end

app/models/category.rb
class Category < ActiveRecord::Base

  include TheSortableTree::Scopes

  has_many :courses

  acts_as_nested_set

  attr_accessible :name, :parent_id, :lft, :rgt

end

app/models/course.rb
class Course < ActiveRecord::Base

  belongs_to :category

  has_many :articles

  has_many :tests

  include TesterModels::StateMachine

end

app/models/question.rb
class Question < ActiveRecord::Base

  belongs_to :test

  has_many :answers, :dependent => :delete_all

  attr_accessible :answers_attributes

  accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a[:title].blank? }, :allow_destroy => true

  include TesterModels::StateMachine

end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/test.rb
class Test < ActiveRecord::Base

  belongs_to :course

  has_many :questions, :dependent => :delete_all

  attr_accessible :questions_attributes

  accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:title].blank? }, :allow_destroy => true

  include TesterModels::StateMachine

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  attr_accessible :username, :email, :password, :password_confirmation, :user_type, :authentications_attributes
  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end

  has_many :authentications, :dependent => :destroy
  accepts_nested_attributes_for :authentications

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_presence_of :username
  validates_uniqueness_of :email

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  include TesterControllers::StateMachine

  # GET /articles
  def index
    if params[:format] == 'json'
      render :json => ArticlesDatatable.new(view_context)
    else
      per_page = if params[:per_page]
        params[:per_page]
      else
        5
      end
      @articles = if params[:course_id] 
        Article.where(:course_id => params[:course_id]).order("id").page(params[:page]).per(per_page)
      else
        Article.all.order("id").page(params[:page]).per(per_page)
      end
    end
  end

  # GET /articles/1
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
    if request.xhr?
      render layout: false
    end
  end

  # GET /articles/1/edit
  def edit
    if request.xhr?
      render layout: false
    end
  end

  # POST /articles
  def create
    @article = Article.new(article_params)

    if @article.save
      if request.xhr?
        return render(:show, :layout => false, notice: 'Article was successfully created.')
      else
        redirect_to @article, notice: 'Article was successfully created.'
      end
    else
      if request.xhr?
        render json: { :errors => @article.errors.full_messages }, status: 422
      else
        render action: 'new'
      end
    end
  end

  # PATCH/PUT /articles/1
  def update
    if !!params[:pk]
      define_state_for_object()
    else
      if @article.update(article_params)
        redirect_to @article, notice: 'Article was successfully updated.'
      else
        render action: 'edit'
      end
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    if request.xhr?
      render inline: 'Ok'
    else
      redirect_to articles_url
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:id, :title, :short, :full, :image_url, :state, :picture, :course_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/render_tree_helper.rb
# DOC:
# We use Helper Methods for tree building,
# because it's faster than View Templates and Partials

# SECURITY note
# Prepare your data on server side for rendering
# or use h.html_escape(node.content)
# for escape potentially dangerous content
module RenderTreeHelper
  class Render
    class << self
      attr_accessor :h, :options

      def render_node(h, options)
        @h, @options = h, options

        node = options[:node]
        "
          <li>
            <div class='item'>
              #{ show_link }
            </div>
            #{ children }
          </li>
        "
      end

      def show_link
        node = options[:node]
        ns   = options[:namespace]
        url  = h.url_for(ns + [node])
        title_field = options[:title]

        "<h4>#{ h.link_to(node.send(title_field), url) }</h4>"
      end

      def children
        unless options[:children].blank?
          "<ol>#{ options[:children] }</ol>"
        end
      end

    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.haml
= form_for @article, :remote => !!params[:remote], :html => { :class => 'form-horizontal articles', :multipart => true, } do |f|
  .control-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text_field'
  .control-group
    = f.label :short, :class => 'control-label'
    .controls
      = f.text_area :short, :class => 'text_field wysihtml5', :rows => "10"
  .control-group
    = f.label :full, :class => 'control-label'
    .controls
      = f.text_area :full, :class => 'text_field wysihtml5', :rows => "10"
  .control-group
    = f.label :state, :class => 'control-label'
    .controls
      = f.select :state, ['draft', 'published']
  .control-group
    = f.label :course_id, :class => 'control-label'
    .controls
      = f.collection_select :course_id, Course.all, :id, :title
  -unless !!params[:remote]
    .control-group
      = f.label :picture, :class => 'control-label'
      .controls
        #uniform-undefined.uploader
          = f.file_field :picture
          %span.filename No file selected
          %span.action Choose File

  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), articles_path, :class => 'btn cancel'

app/views/articles/edit.html.haml
- model_class = Article
- content_for :header do
  =t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")

- content_for :breadcrumbs do
  #breadcrumb
    = link_to '/' do
      %i.icon-home
      Home
    = link_to articles_url do
      %i.icon-file
      Articles
    = link_to '#' do
      %i.icon-edit
      Edit

- unless !!params[:remote]
  .widget-box
    .widget-title
      %h5 Edit article
    .widget-content.nopadding
      = render :partial => "form"
- else
  = render :partial => "form"

app/views/articles/index.html.haml
- model_class = Article
- content_for :header do
  =t '.title', :default => model_class.model_name.human.pluralize

- content_for :breadcrumbs do
  #breadcrumb
    = link_to '/' do
      %i.icon-home
      Home
    = link_to articles_url do
      %i.icon-file
      Articles

.widget-box
  .widget-title
    %h5 Articles list
  .widget-content.nopadding
    %table.table.table-striped.table-bordered.data-table.dataTable{:'data-source' => "#{articles_url(format: "json")}", :id => 'articles'}
      %thead
        %tr
          %th
          %th= model_class.human_attribute_name(:updated_at)
          %th= model_class.human_attribute_name(:title)
          %th= model_class.human_attribute_name(:short)
          %th= model_class.human_attribute_name(:image_url)
          %th= model_class.human_attribute_name(:state)
          %th= model_class.human_attribute_name(:course_id)
          %th=t '.actions', :default => t("helpers.actions")
      %tbody

= link_to t('.new', :default => t("helpers.links.new")), new_article_path, :class => 'btn btn-primary'

app/views/articles/new.html.haml
- model_class = Article
- content_for :header do
  =t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")

- content_for :breadcrumbs do
  #breadcrumb
    = link_to '/' do
      %i.icon-home
      Home
    = link_to articles_url do
      %i.icon-file
      Articles
    = link_to '#' do
      %i.icon-plus-sign
      New

= render :partial => "form"

app/views/articles/show.html.haml
- model_class = Article
- content_for :header do
  =t '.title', :default => model_class.model_name.human

- content_for :breadcrumbs do
  #breadcrumb
    = link_to '/' do
      %i.icon-home
      Home
    = link_to articles_url do
      %i.icon-file
      Articles
    = link_to article_url(@article) do
      %i.icon-file
      Article

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @article.title
%p
  %strong= model_class.human_attribute_name(:short) + ':'
  %br
  = @article.short
%p
  %strong= model_class.human_attribute_name(:full) + ':'
  %br
  = @article.full
%p
  %strong= model_class.human_attribute_name(:state) + ':'
  %br
  = @article.state
%p
  %strong= model_class.human_attribute_name(:course_id) + ':'
  %br
  = @article.course_id
%p
  %strong= model_class.human_attribute_name(:picture) + ':'
  %br
    = image_tag @article.picture.url(:thumb)


.form-actions
  = link_to 'Edit', edit_article_path(@article), :class => 'btn edit'
  = link_to 'Delete', article_path(@article), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger delete'