config/routes.rb
RailsTest::Application.routes.draw do
  get "oauths/oauth"
  get "oauths/callback"
  resources :answers

  resources :questions do
    resources :answers, :shallow => true
  end

  resources :tests do
    resources :questions, :shallow => true
  end

  resources :articles

  resources :posts

  resources :courses do 
    resources :tests, :shallow => true
    resources :articles, :shallow => true
  end


  root to: 'welcome#index'

  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  #resources :users
  post 'users' => "users#create"
  resources :sessions
  resources :password_resets

  scope "/admin" do
    resources :users
    get '/categories' => 'categories#admin_index'
    get '/courses' => 'courses#admin_index'
    get '/tests' => 'tests#admin_index'
  end

  resources :categories, :except => [:admin_index] do
    collection do
      get :manage

      # required for Sortable GUI server side actions
      post :rebuild
    end
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base

  belongs_to :question

end

app/models/article.rb
class Article < ActiveRecord::Base

  attr_accessible :title, :short, :full, :picture, :state, :created_at, :updated_at, :course_id

  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  #validates_attachment_presence :picture

  validates_presence_of :title, :state, :course

  belongs_to :course

  include TesterModels::StateMachine

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  attr_accessible :user_id, :provider, :uid
  belongs_to :user
end

app/models/category.rb
class Category < ActiveRecord::Base

  include TheSortableTree::Scopes

  has_many :courses

  acts_as_nested_set

  attr_accessible :name, :parent_id, :lft, :rgt

end

app/models/course.rb
class Course < ActiveRecord::Base

  belongs_to :category

  has_many :articles

  has_many :tests

  include TesterModels::StateMachine

end

app/models/question.rb
class Question < ActiveRecord::Base

  belongs_to :test

  has_many :answers, :dependent => :delete_all

  attr_accessible :answers_attributes

  accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a[:title].blank? }, :allow_destroy => true

  include TesterModels::StateMachine

end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/test.rb
class Test < ActiveRecord::Base

  belongs_to :course

  has_many :questions, :dependent => :delete_all

  attr_accessible :questions_attributes

  accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:title].blank? }, :allow_destroy => true

  include TesterModels::StateMachine

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  attr_accessible :username, :email, :password, :password_confirmation, :user_type, :authentications_attributes
  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end

  has_many :authentications, :dependent => :destroy
  accepts_nested_attributes_for :authentications

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_presence_of :username
  validates_uniqueness_of :email

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  def index
    #@answers = Answer.all
    @answers = params[:question_id] ? Answer.where(:question_id => params[:question_id]) : Answer.all
  end

  # GET /answers/1
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  def create
    @answer = Answer.new(answer_params)

    if @answer.save
      redirect_to @answer, notice: 'Answer was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /answers/1
  def update
    if @answer.update(answer_params)
      redirect_to @answer, notice: 'Answer was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /answers/1
  def destroy
    @answer.destroy
    redirect_to answers_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:title, :correct, :state)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/render_tree_helper.rb
# DOC:
# We use Helper Methods for tree building,
# because it's faster than View Templates and Partials

# SECURITY note
# Prepare your data on server side for rendering
# or use h.html_escape(node.content)
# for escape potentially dangerous content
module RenderTreeHelper
  class Render
    class << self
      attr_accessor :h, :options

      def render_node(h, options)
        @h, @options = h, options

        node = options[:node]
        "
          <li>
            <div class='item'>
              #{ show_link }
            </div>
            #{ children }
          </li>
        "
      end

      def show_link
        node = options[:node]
        ns   = options[:namespace]
        url  = h.url_for(ns + [node])
        title_field = options[:title]

        "<h4>#{ h.link_to(node.send(title_field), url) }</h4>"
      end

      def children
        unless options[:children].blank?
          "<ol>#{ options[:children] }</ol>"
        end
      end

    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/answers/_form.html.haml
= form_for @answer, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text_field'
  .control-group
    = f.label :correct, :class => 'control-label'
    .controls
      = f.text_field :correct, :class => 'text_field'
  .control-group
    = f.label :question_id, :class => 'control-label'
    .controls
      = f.text_field :question_id, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), answers_path, :class => 'btn'

app/views/answers/edit.html.haml
- model_class = Answer
- content_for :header do
  =t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/answers/index.html.haml
- model_class = Answer
- content_for :header do
  =t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:correct)
      %th= model_class.human_attribute_name(:question_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @answers.each do |answer|
      %tr
        %td= link_to answer.id, answer_path(answer)
        %td= answer.title
        %td= answer.correct
        %td= answer.question_id
        %td=l answer.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_answer_path(answer), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), answer_path(answer), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_answer_path, :class => 'btn btn-primary'

app/views/answers/new.html.haml
- model_class = Answer
- content_for :header do
  =t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/answers/show.html.haml
- model_class = Answer
- content_for :header do
  =t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @answer.title
%p
  %strong= model_class.human_attribute_name(:correct) + ':'
  %br
  = @answer.correct
%p
  %strong= model_class.human_attribute_name(:question_id) + ':'
  %br
  = @answer.question_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), answers_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_answer_path(@answer), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), answer_path(@answer), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'