config/routes.rb
RailsTest::Application.routes.draw do
  get "oauths/oauth"
  get "oauths/callback"
  resources :answers

  resources :questions do
    resources :answers, :shallow => true
  end

  resources :tests do
    resources :questions, :shallow => true
  end

  resources :articles

  resources :posts

  resources :courses do 
    resources :tests, :shallow => true
    resources :articles, :shallow => true
  end


  root to: 'welcome#index'

  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  #resources :users
  post 'users' => "users#create"
  resources :sessions
  resources :password_resets

  scope "/admin" do
    resources :users
    get '/categories' => 'categories#admin_index'
    get '/courses' => 'courses#admin_index'
    get '/tests' => 'tests#admin_index'
  end

  resources :categories, :except => [:admin_index] do
    collection do
      get :manage

      # required for Sortable GUI server side actions
      post :rebuild
    end
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base

  belongs_to :question

end

app/models/article.rb
class Article < ActiveRecord::Base

  attr_accessible :title, :short, :full, :picture, :state, :created_at, :updated_at, :course_id

  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  #validates_attachment_presence :picture

  validates_presence_of :title, :state, :course

  belongs_to :course

  include TesterModels::StateMachine

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  attr_accessible :user_id, :provider, :uid
  belongs_to :user
end

app/models/category.rb
class Category < ActiveRecord::Base

  include TheSortableTree::Scopes

  has_many :courses

  acts_as_nested_set

  attr_accessible :name, :parent_id, :lft, :rgt

end

app/models/course.rb
class Course < ActiveRecord::Base

  belongs_to :category

  has_many :articles

  has_many :tests

  include TesterModels::StateMachine

end

app/models/question.rb
class Question < ActiveRecord::Base

  belongs_to :test

  has_many :answers, :dependent => :delete_all

  attr_accessible :answers_attributes

  accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a[:title].blank? }, :allow_destroy => true

  include TesterModels::StateMachine

end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/test.rb
class Test < ActiveRecord::Base

  belongs_to :course

  has_many :questions, :dependent => :delete_all

  attr_accessible :questions_attributes

  accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:title].blank? }, :allow_destroy => true

  include TesterModels::StateMachine

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  attr_accessible :username, :email, :password, :password_confirmation, :user_type, :authentications_attributes
  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end

  has_many :authentications, :dependent => :destroy
  accepts_nested_attributes_for :authentications

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_presence_of :username
  validates_uniqueness_of :email

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  include TesterControllers::StateMachine

  # GET /courses
  def index
    @courses = Course.all
  end

  # GET /admin/courses
  def admin_index
    if params[:format] == 'json'
      render :json => CoursesDatatable.new(view_context)
    else
      per_page = if params[:per_page]
        params[:per_page]
      else
        5
      end
      @courses = if params[:course_id] 
        Course.where(:course_id => params[:course_id]).order("id").page(params[:page]).per(per_page)
      else
        Course.all.order("id").page(params[:page]).per(per_page)
      end
    end
  end

  # GET /courses/1
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to @course, notice: 'Course was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /courses/1
  def update
    if !!params[:pk]
      define_state_for_object()
    else
      if @course.update(course_params)
        redirect_to @course, notice: 'Course was successfully updated.'
      else
        render action: 'edit'
      end
    end
  end

  # DELETE /courses/1
  def destroy
    @course.destroy
    redirect_to courses_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:title, :short, :full, :state)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/courses/_article.html.haml
%p
  %strong Title
  %br
  = article.title
%p
  %strong Short
  %br
  = article.short
%p
  %strong Full
  %br
  = article.full
%p
  %strong State
  %br
  = article.state
%p
  %strong Picture
  %br
    = image_tag article.picture.url

.form-actions
  = link_to 'Edit', "#{edit_article_path(article)}?remote=true", :class => 'btn edit', :remote => true
  = link_to 'Delete', "#{article_path(article)}?remote=true",  :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger delete', :remote => true

app/views/courses/_create_form.html.haml
= form_for @course, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text_field'
  .control-group
    = f.label :short, :class => 'control-label'
    .controls
      = f.text_field :short, :class => 'text_field'
  .control-group
    = f.label :full, :class => 'control-label'
    .controls
      = f.text_field :full, :class => 'text_field'
  .control-group
    = f.label :state, :class => 'control-label'
    .controls
      = f.text_field :state, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), courses_path, :class => 'btn'

app/views/courses/_edit_form.html.haml
= form_for @course, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text_field'
  .control-group
    = f.label :short, :class => 'control-label'
    .controls
      = f.text_area :short, :class => 'text_field wysihtml5', :rows => "10"
  .control-group
    = f.label :full, :class => 'control-label'
    .controls
      = f.text_area :full, :class => 'text_field wysihtml5', :rows => "10"
  .control-group
    = f.label :state, :class => 'control-label'
    .controls
      = f.select :state, ['draft', 'published']
  .control-group
    %label.control-label 
      Articles and Tests
    .controls
      .accordion{:id => 'accordion1'}
        .widget-box.accordion-group.tabbable
          .accordion-heading
            .widget-title
              %a{:'data-toggle' => "collapse", :'data-parent' => "#accordion1", :href => "#collapseOne", :class => 'collapseOne'}
                %span.icon.pre_accordeon
                  %i.icon-file
                %h5.pre_accordeon
                  Articles 
              %ul.nav.nav-tabs{:id => 'myTab'}
                - @course.articles.each_with_index do |article, index|
                  - if index == 0
                    %li.active
                      =link_to "#{article.title}", "#tab#{index+1}", :'data-toggle' => 'tab'
                  -else
                    %li
                      =link_to "#{article.title}", "#tab#{index+1}", :'data-toggle' => 'tab'
          .accordion-body.collapse{:id => 'collapseOne'}
            .widget-content.nopadding.tab-content
              - @course.articles.each_with_index do |article, index|
                - if index == 0
                  .tab-pane.active{:id => "tab#{index+1}"}
                    = render :partial => 'article', :object => article
                - else
                  .tab-pane{:id => "tab#{index+1}"}
                    = render :partial => 'article', :object => article


        .widget-box.accordion-group.tabbable
          .accordion-heading
            .widget-title
              %a{:'data-toggle' => "collapse", :'data-parent' => "#accordion1", :href => "#collapseTwo", :class => 'collapseTwo'}
                %span.icon.pre_accordeon
                  %i.icon-th-list
                %h5.pre_accordeon
                  Tests
              %ul.nav.nav-tabs{:id => 'myTab1'}
                - @course.tests.each_with_index do |test, index|
                  - if index == 0
                    %li.active
                      =link_to "#{test.title}", "#tab1#{index+1}", :'data-toggle' => 'tab'
                  -else
                    %li
                      =link_to "#{test.title}", "#tab1#{index+1}", :'data-toggle' => 'tab'
          .accordion-body.collapse{:id => 'collapseTwo'}
            .widget-content.nopadding.tab-content
              - @course.tests.each_with_index do |test, index|
                - if index == 0
                  .tab-pane.active{:id => "tab1#{index+1}"}
                    = render :partial => 'test', :object => test
                - else
                  .tab-pane{:id => "tab1#{index+1}"}
                    = render :partial => 'test', :object => test

  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), courses_path, :class => 'btn'
    = link_to 'Add Article', '#', :class => 'add_articles btn'
    = link_to 'Add Test', '#', :class => 'add_tests btn'

app/views/courses/_form.html.haml
= form_for @course, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text_field'
  .control-group
    = f.label :short, :class => 'control-label'
    .controls
      = f.text_field :short, :class => 'text_field'
  .control-group
    = f.label :full, :class => 'control-label'
    .controls
      = f.text_field :full, :class => 'text_field'
  .control-group
    = f.label :state, :class => 'control-label'
    .controls
      = f.text_field :state, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), courses_path, :class => 'btn'

app/views/courses/_test.html.haml
%p
  %strong
    title
  %br
  = test.title
  = test.id
%p
  %strong
    short
  %br
  = test.short
%p
  %strong
    state
  %br
  = test.state

.form-actions
  = link_to 'Edit', "#{edit_test_path(test)}?remote=true", :class => 'btn edit', :remote => true
  = link_to 'Delete', "#{test_path(test)}?remote=true",  :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger delete', :remote => true

app/views/courses/admin_index.html.haml
- model_class = Course
- content_for :header do
  =t '.title', :default => model_class.model_name.human.pluralize
- model_class = Course
- content_for :header do
  =t '.title', :default => model_class.model_name.human.pluralize

- content_for :breadcrumbs do
  #breadcrumb
    = link_to '/' do
      %i.icon-home
      Home
    = link_to courses_url do
      %i.icon-book
      Courses

.widget-box
  .widget-title
    %h5 Courses list
  .widget-content.nopadding
    %table.table.table-striped.table-bordered.data-table.dataTable{:'data-source' => "/admin/courses.json", :id => 'courses'}
      %thead
        %tr
          %th
          %th= model_class.human_attribute_name(:updated_at)
          %th= model_class.human_attribute_name(:title)
          %th= model_class.human_attribute_name(:short)
          %th= model_class.human_attribute_name(:state)
          %th=t '.actions', :default => t("helpers.actions")
      %tbody


= link_to t('.new', :default => t("helpers.links.new")), new_course_path, :class => 'btn btn-primary'

app/views/courses/edit.html.haml
- model_class = Course
- content_for :header do
  =t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")

- content_for :breadcrumbs do
  #breadcrumb
    = link_to '/' do
      %i.icon-home
      Home
    = link_to '/admin/courses' do
      %i.icon-book
      Courses
    = link_to '#' do
      %i.icon-edit
      Edit

.widget-box
  .widget-title
    %h5 Edit article
  .widget-content.nopadding  
    = render :partial => "edit_form"

app/views/courses/index.html.haml
- model_class = Course
- content_for :header do
  =t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-hover
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:short)
      %th= model_class.human_attribute_name(:full)
      %th= model_class.human_attribute_name(:state)
      %th= model_class.human_attribute_name(:created_at)
  %tbody
    - @courses.each do |course|
      %tr
        %td= link_to course.id, course_path(course)
        %td= course.title
        %td= course.short
        %td= course.full
        %td= course.state
        %td=l course.created_at

app/views/courses/new.html.haml
- model_class = Course
- content_for :header do
  =t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")

- content_for :breadcrumbs do
  #breadcrumb
    = link_to '/' do
      %i.icon-home
      Home
    = link_to '/admin/courses' do
      %i.icon-book
      Courses
    = link_to '#' do
      %i.icon-plus-sign
      New


.widget-box
  .widget-title
    %h5 Edit Course
  .widget-content.nopadding
    = render :partial => "create_form"

app/views/courses/show.html.haml
- model_class = Course
- content_for :header do
  =t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @course.title
%p
  %strong= model_class.human_attribute_name(:short) + ':'
  %br
  = @course.short
%p
  %strong= model_class.human_attribute_name(:full) + ':'
  %br
  = @course.full
%p
  %strong= model_class.human_attribute_name(:state) + ':'
  %br
  = @course.state

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), courses_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_course_path(@course), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), course_path(@course), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'