config/routes.rb
RailsTest::Application.routes.draw do
  get "oauths/oauth"
  get "oauths/callback"
  resources :answers

  resources :questions do
    resources :answers, :shallow => true
  end

  resources :tests do
    resources :questions, :shallow => true
  end

  resources :articles

  resources :posts

  resources :courses do 
    resources :tests, :shallow => true
    resources :articles, :shallow => true
  end


  root to: 'welcome#index'

  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  #resources :users
  post 'users' => "users#create"
  resources :sessions
  resources :password_resets

  scope "/admin" do
    resources :users
    get '/categories' => 'categories#admin_index'
    get '/courses' => 'courses#admin_index'
    get '/tests' => 'tests#admin_index'
  end

  resources :categories, :except => [:admin_index] do
    collection do
      get :manage

      # required for Sortable GUI server side actions
      post :rebuild
    end
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base

  belongs_to :question

end

app/models/article.rb
class Article < ActiveRecord::Base

  attr_accessible :title, :short, :full, :picture, :state, :created_at, :updated_at, :course_id

  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  #validates_attachment_presence :picture

  validates_presence_of :title, :state, :course

  belongs_to :course

  include TesterModels::StateMachine

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  attr_accessible :user_id, :provider, :uid
  belongs_to :user
end

app/models/category.rb
class Category < ActiveRecord::Base

  include TheSortableTree::Scopes

  has_many :courses

  acts_as_nested_set

  attr_accessible :name, :parent_id, :lft, :rgt

end

app/models/course.rb
class Course < ActiveRecord::Base

  belongs_to :category

  has_many :articles

  has_many :tests

  include TesterModels::StateMachine

end

app/models/question.rb
class Question < ActiveRecord::Base

  belongs_to :test

  has_many :answers, :dependent => :delete_all

  attr_accessible :answers_attributes

  accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a[:title].blank? }, :allow_destroy => true

  include TesterModels::StateMachine

end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/test.rb
class Test < ActiveRecord::Base

  belongs_to :course

  has_many :questions, :dependent => :delete_all

  attr_accessible :questions_attributes

  accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:title].blank? }, :allow_destroy => true

  include TesterModels::StateMachine

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  attr_accessible :username, :email, :password, :password_confirmation, :user_type, :authentications_attributes
  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end

  has_many :authentications, :dependent => :destroy
  accepts_nested_attributes_for :authentications

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_presence_of :username
  validates_uniqueness_of :email

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :require_login, only: [:admin_index, :edit, :manage, :update, :destroy, :create]
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  include TheSortableTreeController::Rebuild

  def manage
    @category = Category.nested_set.select('id, name, parent_id').all
  end

  # GET /categories
  def index
    @categories = Category.nested_set.all
  end

  # GET /categories
  def admin_index
    @categories = Category.nested_set.all
  end

  # GET /categories/1
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to categories_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :parent_id, :lft, :rgt)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/render_tree_helper.rb
# DOC:
# We use Helper Methods for tree building,
# because it's faster than View Templates and Partials

# SECURITY note
# Prepare your data on server side for rendering
# or use h.html_escape(node.content)
# for escape potentially dangerous content
module RenderTreeHelper
  class Render
    class << self
      attr_accessor :h, :options

      def render_node(h, options)
        @h, @options = h, options

        node = options[:node]
        "
          <li>
            <div class='item'>
              #{ show_link }
            </div>
            #{ children }
          </li>
        "
      end

      def show_link
        node = options[:node]
        ns   = options[:namespace]
        url  = h.url_for(ns + [node])
        title_field = options[:title]

        "<h4>#{ h.link_to(node.send(title_field), url) }</h4>"
      end

      def children
        unless options[:children].blank?
          "<ol>#{ options[:children] }</ol>"
        end
      end

    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.haml
= form_for @category, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :parent_id, :class => 'control-label'
    .controls
      = f.text_field :parent_id, :class => 'text_field'
  .control-group
    = f.label :lft, :class => 'control-label'
    .controls
      = f.text_field :lft, :class => 'text_field'
  .control-group
    = f.label :rgt, :class => 'control-label'
    .controls
      = f.text_field :rgt, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), categories_path, :class => 'btn'

app/views/categories/admin_index.html.haml
- model_class = Category
- content_for :header do
  =t '.title', :default => model_class.model_name.human.pluralize

%ol.sortable_tree{ data: { max_levels: 5, rebuild_url: rebuild_categories_url } }
  = sortable_tree @categories

= link_to t('.new', :default => t("helpers.links.new")), new_category_path, :class => 'btn btn-primary'

app/views/categories/edit.html.haml
- model_class = Category
- content_for :header do
  =t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/categories/index.html.haml
- model_class = Category
- content_for :header do
  =t '.title', :default => model_class.model_name.human.pluralize

%ol.tree
  = just_tree @categories, :title => :name

app/views/categories/new.html.haml
- model_class = Category
- content_for :header do
  =t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/categories/show.html.haml
- model_class = Category
- content_for :header do
  =t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @category.name
%p
  %strong= model_class.human_attribute_name(:parent_id) + ':'
  %br
  = @category.parent_id
%p
  %strong= model_class.human_attribute_name(:lft) + ':'
  %br
  = @category.lft
%p
  %strong= model_class.human_attribute_name(:rgt) + ':'
  %br
  = @category.rgt

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), categories_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_category_path(@category), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), category_path(@category), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'